# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Code is the Easy Part'
tagline:          'A deeper look at building software systems'
description:      'Description will go here.'
url:              code-is-the-easy-part.github.io

author:
  name:           'Ian Shafer'
  url:            https://twitter.com/ishafe

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/code-is-the-easy-part/code-is-the-easy-part.github.io
